---
- name: install epel repo
  yum:
    name:
      - epel-release
    state: present

- name: install centos-release-scl repo
  yum:
    name:
      - centos-release-scl
    state: present
  when: ansible_distribution == "CentOS"

- name: Install remi repo
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
    state: present
  when: ansible_distribution == "CentOS"

- name: Import remi GPG key
  rpm_key:
    key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    state: present
  when: ansible_distribution == "CentOS"

- name: Install packages
  yum:
    name: 
      - mariadb-server
      - wget
      - MySQL-python
      - python-pip
      - policycoreutils-python
      - httpd
    state: latest

- name: install utilities from pip
  pip:
    name:
      - pexpect
    state: present


- name: install php and php modules
  yum:
    name:
      - php{{ php_version }}
      - php{{ php_version }}-php
      - php{{ php_version }}-php-curl
      - php{{ php_version }}-php-fileinfo
      - php{{ php_version }}-php-gd
      - php{{ php_version }}-php-json
      - php{{ php_version }}-php-mbstring
      - php{{ php_version }}-php-mysqli
      - php{{ php_version }}-php-session
      - php{{ php_version }}-php-zlib
      - php{{ php_version }}-php-simplexml
      - php{{ php_version }}-php-xml
      - php{{ php_version }}-php-cli
      - php{{ php_version }}-php-domxml
      - php{{ php_version }}-php-imap
      - php{{ php_version }}-php-ldap
      - php{{ php_version }}-php-openssl
      - php{{ php_version }}-php-xmlrpc
      - php{{ php_version }}-php-APCu
    state: present

- name: start Mariadb
  service:
    name: mariadb
    state: started
    enabled: yes

- name: start Apache
  service:
    name: httpd
    state: started
    enabled: yes

- name: Secure the MySQL root user
  mysql_user:
    name: root
    host: "{{ item }}"
    login_user: root
  with_items:
    - 127.0.0.1
    - localhost
    - ::1

- name: Secure the MySQL root user with a password
  mysql_user:
    name: root
    password: "{{ glpi_root_database_password }}"
    login_user: root

- name: Delete anonymous MySQL server user for localhost
  mysql_user:
    name: ""
    state: absent
    login_password: "{{ glpi_root_database_password }}"
    login_user: root

- name: Remove the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_password: "{{ glpi_root_database_password }}"
    login_user: root

- name: create database
  mysql_db:
    name: "{{ glpi_database_name }}"
    state: present

- name: Create database user and grant privileges
  mysql_user:
    name: "{{ glpi_database_user }}"
    password: "{{ glpi_database_pass }}"
    priv: "{{ glpi_database_name }}.*:ALL"
    state: present

- name: restart Mariadb
  service:
    name: mariadb
    state: restarted

- name: edit php.ini
  lineinfile:
    path: "{{ phpinipath }}"
    regexp: '^memory_limit'
    line: memory_limit = {{ memorylimit }}M

- name: edit php.ini
  lineinfile:
    path: "{{ phpinipath }}"
    regexp: '^file_uploads'
    line: file_uploads = on

- name: edit php.ini
  lineinfile:
    path: "{{ phpinipath }}"
    regexp: '^max_execution_time'
    line: max_execution_time = {{ max_execution_time }}

- name: edit php.ini
  lineinfile:
    path: "{{ phpinipath }}"
    regexp: '^register_globals'
    line: register_globals = off

- name: edit php.ini
  lineinfile:
    path: "{{ phpinipath }}"
    regexp: '^magic_quotes_sybase'
    line: magic_quotes_sybase = off

- name: edit php.ini
  lineinfile:
    path: "{{ phpinipath }}"
    regexp: '^session.auto_start'
    line: session.auto_start = off

- name: edit php.ini
  lineinfile:
    path: "{{ phpinipath }}"
    regexp: '^session.use_trans_sid'
    line: session.use_trans_sid = 0 